# Generated by Django 6.0.2 on 2026-02-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsummary",
            name="type_distribution",
            field=models.JSONField(default=dict),
        ),
    ]
